import assert from 'node:assert/strict';
import test from 'node:test';
import type { PreparedBrowserProjection, ProjectionManifestV2, SceneIR } from '../src/index.js';
import { project, renderProjection } from '../src/index.js';

const scene: SceneIR = { schemaVersion:'0.1.0',layoutVersion:'m3e',seed:'m3e',inputHash:`sha256:${'e'.repeat(64)}`,nodes:[{id:'node:b',semanticKind:'course',label:'B',position:{x:1,y:0,z:1},focusOrder:2,capabilities:['inspect']},{id:'node:a',semanticKind:'program',label:'A',position:{x:0,y:0,z:0},focusOrder:1,capabilities:['inspect']}],edges:[{id:'edge:a-b',semanticKind:'CONTAINS',source:'node:a',target:'node:b'}] };
function prepared(manifest:ProjectionManifestV2):PreparedBrowserProjection<string>{return{roots:['root'],nodeIds:[...manifest.nodeIds],edgeIds:[...manifest.edgeIds],focusOrderNodeIds:[...manifest.focusOrderNodeIds],nodeDescriptors:manifest.nodeDescriptors.map((v)=>({...v})),edgeDescriptors:manifest.edgeDescriptors.map((v)=>({...v}))};}
function ports(manifest:ProjectionManifestV2, value=prepared(manifest)){return{dom:{prepareHtml(){return value;},prepareSvg(){return value;}},three:{prepareThree(){return value;}}};}
for(const kind of ['html','svg','three'] as const)test(`${kind} validates trusted semantic descriptors before one commit`,()=>{const manifest=project(scene,kind);let calls=0;const receipt=renderProjection(manifest,{replaceChildren(){calls+=1;}},ports(manifest));assert.equal(calls,1);assert.equal(receipt.schemaVersion,'1.0.0');assert.deepEqual(receipt.nodeIds,['node:a','node:b']);});

test('rejects forged prepared node descriptor before target mutation',()=>{const manifest=project(scene,'html');const value=prepared(manifest);value.nodeDescriptors[0]={...value.nodeDescriptors[0]!,label:'forged'};let calls=0;assert.throws(()=>renderProjection(manifest,{replaceChildren(){calls+=1;}},ports(manifest,value)),/BROWSER_RENDER_NODE_DESCRIPTORS_MISMATCH/);assert.equal(calls,0);});
test('rejects forged prepared edge endpoint before target mutation',()=>{const manifest=project(scene,'svg');const value=prepared(manifest);value.edgeDescriptors[0]={...value.edgeDescriptors[0]!,target:'node:a'};let calls=0;assert.throws(()=>renderProjection(manifest,{replaceChildren(){calls+=1;}},ports(manifest,value)),/BROWSER_RENDER_EDGE_DESCRIPTORS_MISMATCH/);assert.equal(calls,0);});
test('rejects missing, duplicate, and reordered manifest descriptors before preparation',()=>{for(const mutate of [(m:ProjectionManifestV2)=>({...m,nodeDescriptors:undefined}),(m:ProjectionManifestV2)=>({...m,nodeDescriptors:[m.nodeDescriptors[0],m.nodeDescriptors[0]]}),(m:ProjectionManifestV2)=>({...m,nodeDescriptors:[...m.nodeDescriptors].reverse()})]){const base=project(scene,'html');const manifest=mutate(base) as ProjectionManifestV2;let preparedCalls=0,targetCalls=0;assert.throws(()=>renderProjection(manifest,{replaceChildren(){targetCalls+=1;}},{dom:{prepareHtml(){preparedCalls+=1;return prepared(base);},prepareSvg(){preparedCalls+=1;return prepared(base);}}}),/BROWSER_RENDER_INVALID_MANIFEST:nodeDescriptors:(type|duplicate|unsorted)/);assert.equal(preparedCalls,0);assert.equal(targetCalls,0);}});
test('derives Three node and edge semantics before calling injected port',()=>{for(const mutate of [(payload:any)=>{payload.nodes[0].label='drift';},(payload:any)=>{payload.nodes[0].semanticKind='drift';},(payload:any)=>{payload.edges[0].target='node:a';}]){const base=project(scene,'three');const payload=JSON.parse(base.content);mutate(payload);const manifest={...base,content:JSON.stringify(payload)};let portCalls=0,targetCalls=0;assert.throws(()=>renderProjection(manifest,{replaceChildren(){targetCalls+=1;}},{dom:{prepareHtml(){throw new Error('unused');},prepareSvg(){throw new Error('unused');}},three:{prepareThree(){portCalls+=1;return prepared(base);}}}),/BROWSER_RENDER_(NODE|EDGE)_DESCRIPTORS_MISMATCH/);assert.equal(portCalls,0);assert.equal(targetCalls,0);}});
